templates:
  - id: diagnosis
    name: "אבחון"
    required_headers:
      - "רקע:"
      - "מהלך האבחון:"
      - "ממצאי האבחון:"
      - "סיכום והמלצות:"
    section_headers:
      - "רקע:"
      - "מהלך האבחון:"
      - "ממצאי האבחון:"
      - "סיכום והמלצות:"
      - "תמצית אבחון"

  - id: treatment_plan
    name: "תוכנית טיפול"
    required_headers:
      - "מטרת על:"
      - "הערות:"
    section_headers:
      - "מטרת על:"
      - "הערות:"
      - "מטרות בתאריך"